### ISSUE TITLE
Crear animación del nav

### ISSUE THREAD

**Issue by sebastinez** [sebastinez/grupo8-e-commerce#15]
El nav debe al hacer scroll hacia abajo volverse menos traslucido y reducir su altura de 100px a 60px.
Asi se evita que el texto del header queda legible debajo del nav.

**Comment by sebastinez** [comment]
Se implemento un primer desarrollo con el commit af30e5ee. Se requiere mejor la suavidad de la animación en un futuro.. Mantengo el issue abierto.

**Comment by ezequielstuarts** [comment]
Se resolvió la transition del nav y cambio de opacidad con el commit 548c12a3.
