### ISSUE TITLE
Cambio de logo G6 por G8?

### ISSUE THREAD

**Issue by sebastinez** [sebastinez/grupo8-e-commerce#18]
Me parece que el logo G6 como grupo 6 lo deberiamos cambiar por G8, que les parece?

![logo-g6](https://user-images.githubusercontent.com/7912302/64524585-36287980-d2d5-11e9-8cb3-c4ecb109e59c.png)

**Comment by ezequielstuarts** [comment]
Se hizo el cambio del logo y se aplico como icono tambien.
