### ISSUE TITLE
Fondo Imagen

### ISSUE THREAD

**Issue by ezequielstuarts** [sebastinez/grupo8-e-commerce#22]
Reveer o plantrear, tema de imagen de fondo, se pixela y se mueve

**Comment by sebastinez** [comment]
@fedebacino estaba desarrollando una forma cambiando `background-size` y `background-position`
Propongo de mantener la imagen arriba y si alguien extiende la pagina muy para abajo que se encuentre con un fondo negro y una transición de la imagen al fondo negro..

**Comment by ezequielstuarts** [comment]
Commit 7f3e846- Saque la imagen de fondo, que se pixelaba y deje fondo plano

**Comment by ezequielstuarts** [comment]
Commit 7f3e846- Saque la imagen de fondo, que se pixelaba y deje fondo plano
